smote:
  apply: true
  random_state: 42

split:
  test_size: 0.2
  random_state: 42

model:
  params:
    n_estimators: 100
    max_depth: 5
  min_accuracy: 0.80

save:
  model_path: "models/random_forest_model.pkl"

data:
  data_path: "C:/Users/alsan/Customer360_AI/data/customer_360_data.csv"
  target_column: "fraud_risk"
